[package]
name = "MoveCoin"
authors = ["Pika", "10xhunter", "jolestar", "jojoo-eth"]
version = "1.0"
#testnet
published-at = "0x5f354890c0661633e7add642cdecd24c19d6f414b64d8404456698007203987e"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.17.3", override = true}
SmartInscription = { local = "../" }

[addresses]
#testnet
smartinscription = "0x5f354890c0661633e7add642cdecd24c19d6f414b64d8404456698007203987e"
#movecoin = "0x0"
